// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbualkhivfcgfrqqjvzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5idWFsa2hpdmZjZ2ZycXFqdnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODUzMjgsImV4cCI6MjA3MTc2MTMyOH0.rtqjHwudbK0Ef3Lsvwbd7MVnVPhAH8uXjZi6Y2Pd4OA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});